library(tidyverse)										
library(odin)											

# Setup 
source('code/utils.R') 									
source('code/global_parameters.R')						
source('code/parameters.R') 							

# Psi inference
# Viral kinetics inputs: sc2_kinetics_fit.R runs a full MCMC (~tens of minutes to
# hours, several GB RAM) and writes output/posterior_features_single_category.rds;
# sc2_kinetics_figures.R and Fig 2 panel E read that rds without refitting. Once
# the rds exists you can comment out the fit line to skip the slow step.
source('code/sc2_kinetics_fit.R')
source('code/sc2_kinetics_figures.R')
source('code/psi_inference.R')
source('code/psi_cluster_figures.R') 					# Fig 2 (A-E): psi clusters + kinetics window
source('code/psi_identifiability.R')
source('code/psi_identifiability_figures.R')

# Uncontrolled epidemics 
source('code/episims.R') 								
source('code/overdispersion_extinction.R') 				
source('code/overdispersion_heatmaps.R')				
source('code/survival.R')								

# Controlled epidemics 
source('code/isolation_te.R')							
source('code/isolation_overdispersion.R')				
source('code/isolation_gi_truncation.R')				
source('code/isolation_gi_truncation_deterministic.R')	
source('code/isolation_growth_rate.R')
source('code/fig5_figures.R') 							# Fig 5 (B-E): assembles saved isolation panels
source('code/gatheringsize_main.R')
source('code/gatheringsize_od.R')

# General parameter inference
source('code/growthrate.R') 							
source('code/g_identifiability.R')						

# Sensitivity analyses (robustness to burst model choice)
source('code/sensitivity_episims.R')
source('code/sensitivity_overdispersion.R')
source('code/sensitivity_isolation_te.R')
source('code/sensitivity_growthrate.R')
source('code/sensitivity_marginal_gi.R')
source('code/ed_burstmodels_qq.R') 						# ED: QQ grid from the marginal-GI objects

# Extended Data assembly
# Must run last: consumes the per-panel plot objects stashed in figures/_objects/
# by save_fig() above, composites them into the Nature-formatted Extended Data
# figures under figures/ExtendedData/, and copies each into writeup/v7_nature/figures/.
source('code/make_extended_data.R')

# Note on the final figures:
#   This pipeline reproduces every analysis panel (via save_fig) and all composited
#   Extended Data figures (via make_extended_data.R). The final main-text Figs. 1, 3,
#   and 4 are hand-assembled outside R (Mathematica/Inkscape; e.g. figures/gammapoisson.nb
#   generates Extended Data Fig. 3), and Figs. 2 and 5 are composited by the called
#   scripts psi_cluster_figures.R and fig5_figures.R. The hand-assembled mains are not
#   regenerated by sourcing this file.
